services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
      - /frontend/build
      - /frontend/.next
    ports:
      - "3000:3000"